// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Js_math from "bs-platform/lib/es6/js_math.js";
import * as TodoInput from "../components/TodoInput.bs.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function Todo(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setTodoInput = match[1];
  var todoInput = match[0];
  var match$1 = React.useState(function () {
        return [{
                  id: Js_math.random_int(0, 999),
                  text: "Todo 1"
                }];
      });
  var setTodos = match$1[1];
  var todos = match$1[0];
  var onChange = function (value) {
    return Curry._1(setTodoInput, (function (_prev) {
                  return value;
                }));
  };
  var onSave = function (evt) {
    evt.preventDefault();
    var newTodo_id = Js_math.random_int(0, 999);
    var newTodo = {
      id: newTodo_id,
      text: todoInput
    };
    var newTodoList = [newTodo].concat(todos);
    return Curry._1(setTodos, (function (_prev) {
                  return newTodoList;
                }));
  };
  return React.createElement("div", undefined, "Hello Todo List !", React.createElement(TodoInput.make, {
                  todoText: todoInput,
                  handleChange: onChange
                }), React.createElement("button", {
                  onClick: onSave
                }, "save"), Belt_Array.map(todos, (function (todo) {
                    return React.createElement("div", {
                                key: String(todo.id)
                              }, React.createElement("button", {
                                    onClick: (function (evt) {
                                        var id = todo.id;
                                        evt.preventDefault();
                                        var res = todos.filter(function (x) {
                                              return x.id !== id;
                                            });
                                        return Curry._1(setTodos, (function (_prev) {
                                                      return res;
                                                    }));
                                      })
                                  }, "X"), " -- ", todo.text);
                  })));
}

var make = Todo;

export {
  make ,
  
}
/* react Not a pure module */
