// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function TodoInput(Props) {
  var todoText = Props.todoText;
  var handleChange = Props.handleChange;
  var onChange = function (evt) {
    evt.preventDefault();
    return Curry._1(handleChange, evt.target.value);
  };
  return React.createElement("div", undefined, React.createElement("input", {
                  value: todoText,
                  onChange: onChange
                }));
}

var make = TodoInput;

export {
  make ,
  
}
/* react Not a pure module */
